python -u  train.py \
        --base configs/custom-diffusion/finetune_style_joint.yaml  \
        -t --gpus 0,1 \
        --resume-from-checkpoint-custom  ./sd-v1-4.ckpt \
        --caption "<cat2> cat" \
        --datapath "Data/concept_image/cat2" \
        --reg_datapath "real_reg/cat2/images.txt" \
        --reg_caption "real_reg/cat2/caption.txt" \
        --caption2 "<dog6> dog" \
        --datapath2 "Data/concept_image/dog6" \
        --reg_datapath2 "real_reg/dog6/images.txt" \
        --reg_caption2 "real_reg/dog6/caption.txt" \
        --modifier_token "<cat2>+<dog6>" \
        --name "dlcv-final-custom0-sdv4" \
        --batch_size 2 \
        --logdir "/tmp2/seanfu/logdir"