python -u  train.py \
        --base configs/custom-diffusion/finetune_style_joint.yaml  \
        -t --gpus 0,1 \
        --resume-from-checkpoint-custom  ./sd-v1-4.ckpt \
        --caption "<flower_1> flower" \
        --datapath "Data/concept_image/flower_1" \
        --reg_datapath "real_reg/flower_1/images.txt" \
        --reg_caption "real_reg/flower_1/caption.txt" \
        --caption2 "<vase> vase" \
        --datapath2 "Data/concept_image/vase" \
        --reg_datapath2 "real_reg/vase/images.txt" \
        --reg_caption2 "real_reg/vase/caption.txt" \
        --modifier_token "<flower_1>+<vase>" \
        --name "dlcv-final-custom1-sdv4" \
        --batch_size 2 \
        --logdir "/tmp2/seanfu/logdir"