python -u  train.py \
        --base configs/custom-diffusion/finetune_style_joint3.yaml  \
        -t --gpus 0,1 \
        --resume-from-checkpoint-custom  ./sd-v1-4.ckpt \
        --caption "<dog> dog" \
        --datapath "Data/concept_image/dog" \
        --reg_datapath "real_reg/dog/images.txt" \
        --reg_caption "real_reg/dog/caption.txt" \
        --caption2 "<pet_cat1> cat" \
        --datapath2 "Data/concept_image/pet_cat1" \
        --reg_datapath2 "real_reg/pet_cat1/images.txt" \
        --reg_caption2 "real_reg/pet_cat1/caption.txt" \
        --caption3 "<dog6> dog" \
        --datapath3 "Data/concept_image/dog6" \
        --reg_datapath3 "real_reg/dog6/images.txt" \
        --reg_caption3 "real_reg/dog6/caption.txt" \
        --modifier_token "<dog>+<pet_cat1>+<dog6>" \
        --name "dlcv-final-custom2-sdv4" \
        --batch_size 2 \
        --logdir "/tmp2/seanfu/logdir"